### ISSUE TITLE
Support for HTML5

### ISSUE THREAD

**Issue by BenDol** [borup3/Lighting-System-2D#1]
Would be cool to see this working in HTML5 (assuming its not already). I have tried with no luck, however it works fine in Windows.

**Comment by borup3** [comment]
Hi BenDol, I'll take a look probably the week after next to see what's going on.

**Comment by borup3** [comment]
No progress here. It's likely to be bugs in the HTML5 export. There's no reason this shouldn't work correctly out of the box.
