### ISSUE TITLE
macOS issue. light not appearing.

### ISSUE THREAD

**Issue by foxinni** [borup3/Lighting-System-2D#2]
Hi,

This does not seem to work on macOS? 

I'm getting a "lights turned off" look. Someone on youtube also commented on that.

![image](https://user-images.githubusercontent.com/124101/53295625-0c5fa780-3808-11e9-8e92-2b285cb8146f.png)

![image](https://user-images.githubusercontent.com/124101/53295637-50eb4300-3808-11e9-9906-dfb9a8c53a4d.png)

Thanks

**Comment by borup3** [comment]
Hi foxinni, thanks for creating an issue for this. I'm taking a look when I have access to a mac next week, although I'm away tuesday/wednesday/thursday, and I will definitely fix this so it works asap.

**Comment by foxinni** [comment]
Any luck?

**Comment by borup3** [comment]
I've acquired a mac computer and am setting it up to fix this issue...

**Comment by xenonii** [comment]
@borup3 I noticed this issue too. Do you need a hand for debugging this?
I didn't notice any errors in the output when running the demos.

**Comment by borup3** [comment]
I haven't found the time to investigate yet (and I'm busy for the next week...). It's open source, and a good benefit of that is that anyone can lend a helping hand :)

**Comment by xenonii** [comment]
If you had to bet, where should I start looking at? Can you give a pointer
where I could start digging?

**Comment by borup3** [comment]
I would verify the shader first, then move up stream from there

**Comment by foxinni** [comment]
I'm still to new to GMS to really know where to look. Hope you carve out some time for this. Thanks!

**Comment by ajrdesign** [comment]
<img width="1680" alt="Screen Shot 2019-10-27 at 9 57 34 AM" src="https://user-images.githubusercontent.com/2229401/67638305-4655e180-f8a0-11e9-8bf9-edd7701a1513.png">

Looks like this still isn't really working on Mac.

**Comment by harperj0** [comment]
hey all.  after poking around a bit, i think i've isolated the problematic area. the light masks aren't being drawn correctly on the global.worldShadowMap surface which would then be applied to the final surface shown to the player.
The problematic code when it comes to macOS is below line 128 in the composite_shadow_map script run by the light renderer object in the draw event.  i've been struggling with this for a while and hope to find a solution.  learning shader language is on my todo list in case the sh_blend_light shader needs to be rewritten for macOS.

**Comment by Mattbrush** [comment]
Hi there, I'm also looking into this now. Just curious, did you make any headway on the bug ?

**Comment by harperj0** [comment]
> Hi there, I'm also looking into this now. Just curious, did you make any headway on the bug ?

I've been on again off again visiting this issue and troubleshooting.  With assistance from @borup3 on twitter, I found that when run through windows the lighting system creates 2 light related surfaces: one being the actual light masks (colored circles) and the other being the product of taking the application_surface and applying it through the light masks.  various hard-edge shadow surfaces are also created.
when the same project is run through the macos IDE, the 2 light related surfaces mentioned are created but are "empty".  leaving just the hard-edge surfaces and a dimmed screen dependent on what your **global.ambientShadowIntensity** is set to.

_some things I considered:_
- is there a surface_reset_target() function being used every time the shadow map fills a surface?
- are the **eLight.LutIntensity** sprites also being drawn?
- does switching the shader type from GLSL ES to GLSL or even HLSL 11 yield different results?
- does creating a **global.worldCustomCamera** yield different results?
- does switching the compiler to target an VM output to a YYC output change anything?

some definitive differences I've been able to pick out are that in the debbuger, the windows version begins indexing surfaces from 6 onward as if its picking up from the indexing of textures whereas the macos version of the project begins indexing both textures and surfaces from 1 onward.
Thats about all I have about the issue at the moment unfortunately.

**Comment by borup3** [comment]
Hi guys, can you try running this on macOS but in the vertex shaders of sh_blend_list and sh_shadow_map try replacing `in_Texcoord` with `in_TextureCoord`.

**Comment by harperj0** [comment]
> Hi guys, can you try running this on macOS but in the vertex shaders of sh_blend_list and sh_shadow_map try replacing `in_Texcoord` with `in_TextureCoord`.

ladies and gentlemen, he got it

**Comment by harperj0** [comment]
I'm actually in awe right now.  it was the vertex shader all along.  I was so sure it was an error on gm's part when compiling the code then wrapping it.  how did you come to this???

**Comment by borup3** [comment]
GameMaker creates shaders with the attribute name `in_TextureCoord` by default. I'm not sure if they always did that or if I renamed it at one point. Either way, it should work regardless of the name.

@harperj0 Do you mind creating a pull request with the change for me? I'm not presently equipped for it.

**Comment by harperj0** [comment]
@borup3 you got it!  thank you so much for your help!

**Comment by borup3** [comment]
Thanks!
